apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: maduflavins/airbnb-spleet-frontend:tagVersion
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: REACT_APP_BACKEND_URL
        - name: REACT_APP_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: REACT_APP_GOOGLE_CLIENT_ID
        - name: REACT_APP_GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: frontend-secret
              key: REACT_APP_GOOGLE_CLIENT_SECRET